#配置数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://192.168.71.15:3306/skit?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456

      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 10000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: update
#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key

# 文件存储路径
file:
  path: /Volumes/perye/file/dokit/
  avatar: /Volumes/perye/file/dokit/avatar/
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
dingding:
  error-url: https://oapi.dingtalk.com/robot/send?access_token=8d0bea7fe8a5c31d60a22223e5012ef64db4bd51b7e0b24d60b3decb72399c47
  error-key: 栎尚网络skit
baidubos:
  access_key_id: b0a31c04625d470187a7e0a0719d8689
  secret_access_key: bfe5b63631fd4248bbcbe97ba7203ddf
  endpoint: http://gz.bcebos.com
  bucketName:
    public: yueshang-skit-public
    private: yueshang-skit
# 创蓝短信
chuanglan:
  smsvariablerequesturl: http://smssh1.253.com/msg/variable/json
  msg: 【锦超网络】尊敬的{$var},您好,您的验证码是{$var},{$var}分钟内有效
  account: YZM5253741
  pswd: lSFYvjCHyJ53b4
  sign: 栎尚
  time: 3
sharelink:
  priKeyPass: 123
  #windows环境商户证书路径
  priKeyPath: D:/config/test/ect_test.pfx
  #windows环境平台证书路径
  pubKeyPath: D:/config/test/ect_test.cer